---
language: "go"
go:
  - "1.4.2"
  - "tip"

env:
  - # test using defaults
  - DB_DIALECT="postgres" DB_DATASOURCE="host=127.0.0.1 user=postgres dbname=leavediary_test sslmode=disable"

addons:
  postgresql: "9.4"

before_script:
  psql -c "CREATE DATABASE leavediary_test;" -U postgres

matrix:
  allow_failures:
    - go: "tip"

script: "make test"

notifications:
  email: false

# Enable faster container builds: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
